# Generated by Django 4.2.5 on 2024-05-10 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_visitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='count',
            new_name='daily_count',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='visited_at',
        ),
        migrations.AddField(
            model_name='visitor',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='visitor',
            name='monthly_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitor',
            name='total_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
