# Generated by Django 4.2.5 on 2024-05-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('daily_count', models.PositiveIntegerField(default=0)),
                ('weekly_count', models.PositiveIntegerField(default=0)),
                ('monthly_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
