# Generated by Django 4.2.5 on 2024-05-10 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_visitor_delete_visitorcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
