# Generated by Django 5.0 on 2023-12-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyxel', '0002_answer_author_question_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
