# Generated by Django 5.0 on 2024-03-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyxel', '0007_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='recommendation',
            field=models.IntegerField(choices=[(1, '호반베르디움 1차'), (2, '호반베르디움 2차'), (3, '호반베르디움 3차'), (4, '호반베르디움 4차')], default=1),
        ),
    ]
