# Generated by Django 5.0 on 2024-04-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyxel', '0008_question_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='recommendation',
        ),
    ]
