# Generated by Django 5.0 on 2024-05-07 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyxel', '0011_questionimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionImage',
        ),
    ]
